# Generated by Django 3.2.8 on 2023-01-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article_images',
            name='img',
            field=models.ImageField(upload_to='article_images'),
        ),
    ]
