# Generated by Django 3.2.8 on 2023-01-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_images_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img_title',
            field=models.ImageField(blank=True, null=True, upload_to='article_images_title'),
        ),
    ]
