# Generated by Django 3.2.8 on 2023-01-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
