# Generated by Django 3.2.8 on 2023-01-31 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_delete_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introduction',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='introduction',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video_introduction'),
        ),
    ]
